/*
 * CMSgov CMSDS Component Theme
 */

import { default as t } from './cmsgov'
import { hexOpacity } from '../lib/colorUtils'
import { AnyTokenValues } from '../lib/types'

// Write a little script that goes through each component and turns each property into an object
// with a type derived by pattern matching the property name.
// if prefixed with __, it goes in the current object
// if prefixed with -, it goes in a new sub-object (not in a siblng object, because we want to
//   maintain the hierarchy)

export const components: AnyTokenValues = {
  'accordion': {
    '__color':                                    { "$value": "{theme.color.base}" },
    '__background-color':                         { "$value": "{theme.color.primary.lightest}" },
    '__background-color--hover':                  { "$value": "{theme.color.primary.lighter}" },
    '__border-color':                             { "$value": "{theme.color.gray.lightest}" },
    '__border-radius':                            '20px 20px 0 0',
    '__border-width':                             '1px',
    '-button__color':                             { "$value": "{theme.color.base}" },
    '-content__background-color':                 { "$value": "{theme.color.white}" },
  },

  'alert': {
    '__background-color':                         { "$value": "{theme.color.info.lightest}" },
    '__background-color--error':                  { "$value": "{theme.color.error.lightest}" },
    '__background-color--lightweight':            { "$value": "{theme.color.white}" },
    '__background-color--success':                { "$value": "{theme.color.success.lightest}" },
    '__background-color--warn':                   { "$value": "{theme.color.warn.lightest}" },
    '__border-left-color':                        { "$value": "{theme.color.info}" },
    '__border-color--error':                      { "$value": "{theme.color.error}" },
    '__border-color--success':                    { "$value": "{theme.color.success}" },
    '__border-color--warn':                       { "$value": "{theme.color.warn}" },
    '__font-color':                               { "$value": "{theme.color.base}" },
    '__icon-size':                                { "$value": "{spacer.5}" },
    '__padding':                                  { "$value": "{spacer.2}" },
    '-bar__width':                                { "$value": "{spacer.1}" },
    '-link__font-color':                          { "$value": "{theme.color.primary.darker}" },
    '-link__font-color--hover':                   { "$value": "{theme.color.primary.darkest}" },
    '-link__font-color--focus':                   { "$value": "{theme.color.primary.darkest}" },
    '-link__font-color--active':                  { "$value": "{theme.color.primary.darkest}" },
  },

  'autocomplete': {
    '__background-color':                         { "$value": "{theme.color.white}" },
    '__border-color':                             { "$value": "{theme.color.gray.lighter}" },
    '-item__font-color':                          { "$value": "{theme.color.primary}" },
    '-item__background-color--active':            { "$value": "{theme.color.primary}" },
    '-item__font-color--active':                  { "$value": "{theme.color.white}" },
    '-item-message__font-color':                  { "$value": "{theme.color.primary}" },
  },

  'badge': {
    '__background-color':                         { "$value": "{theme.color.gray.lightest}" },
    '__background-color--alert':                  { "$value": "{theme.color.error}" },
    '__background-color--info':                   { "$value": "{theme.color.primary}" },
    '__background-color--success':                { "$value": "{theme.color.success}" },
    '__background-color--warn':                   { "$value": "{theme.color.warn}" },
    '__font-color':                               { "$value": "{theme.color.base}" },
    '__font-color--alert':                        { "$value": "{theme.color.white}" },
    '__font-color--info':                         { "$value": "{theme.color.white}" },
    '__font-color--success':                      { "$value": "{theme.color.white}" },
    '__font-color--warn':                         { "$value": "{theme.color.base}" },
    '__border-radius':                            { "$value": "{radius.medium}" },
  },

  'button': {
    '__background-color--active':                 { "$value": "{theme.color.primary.lightest}" },
    '__background-color--disabled':               { "$value": "{theme.color.gray.lightest}" },
    '__background-color--hover':                  { "$value": "{theme.color.accent.primary}" },
    '__background-color':                         'transparent',
    '__border-color--active':                     { "$value": "{theme.color.primary}" },
    '__border-color--disabled':                   { "$value": "{theme.color.gray.lighter}" },
    '__border-color--hover':                      { "$value": "{theme.color.primary}" },
    '__border-color':                             { "$value": "{theme.color.primary}" },
    '__border-radius':                            { "$value": "{radius.pill}" },
    '__border-width':                             '2px',
    '__color--active':                            { "$value": "{theme.color.primary.darkest}" },
    '__color--disabled':                          { "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$value": "{theme.color.primary.darker}" },
    '__color':                                    { "$value": "{theme.color.primary}" },
    '__font-weight':                              t.font['weight-bold'],
    '-icon__fill':                                'currentColor',
  },

  'button-alt': {
    '__background-color--active':                 { "$value": "{theme.color.gray.lighter}" },
    '__background-color--disabled':               'transparent',
    '__background-color--hover':                  { "$value": "{theme.color.accent.primary}" },
    '__background-color':                         'transparent',
    '__border-color--active':                     'currentColor',
    '__border-color--disabled':                   'currentColor',
    '__border-color--hover':                      'currentColor',
    '__border-color':                             'currentColor',
    '__color--active':                            { "$value": "{theme.color.primary.darkest}" },
    '__color--disabled':                          { "$value": "{theme.color.gray.lighter}" },
    '__color--hover':                             { "$value": "{theme.color.primary.darker}" },
    '__color':                                    { "$value": "{theme.color.primary}" },
  },

  'button-dark': {
    '__background-color--active':                 'transparent',
    '__background-color--disabled':               'transparent',
    '__background-color--hover':                  'transparent',
    '__background-color':                         'transparent',
    '__border-color--active':                     'currentColor',
    '__border-color--disabled':                   'currentColor',
    '__border-color--hover':                      'currentColor',
    '__border-color':                             'currentColor',
    '__color--active':                            { "$value": "{theme.color.gray.lighter}" },
    '__color--disabled':                          { "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$value": "{theme.color.gray.lightest}" },
    '__color':                                    { "$value": "{theme.color.white}" },
  },

  'button-dark-alt': {
    '__background-color--active':                 'transparent',
    '__background-color--disabled':               'transparent',
    '__background-color--hover':                  'transparent',
    '__background-color':                         'transparent',
    '__border-color--active':                     'currentColor',
    '__border-color--disabled':                   'currentColor',
    '__border-color--hover':                      'currentColor',
    '__border-color':                             'currentColor',
    '__color--active':                            { "$value": "{theme.color.secondary.light}" },
    '__color--disabled':                          { "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$value": "{theme.color.secondary.lighter}" },
    '__color':                                    { "$value": "{theme.color.secondary.lightest}" },
  },

  'button-solid': {
    '__background-color--active':                 { "$value": "{theme.color.primary.lightest}" },
    '__background-color--disabled':               { "$value": "{theme.color.gray.lightest}" },
    '__background-color--hover':                  { "$value": "{theme.color.accent.primary}" },
    '__background-color':                         { "$value": "{theme.color.primary}" },
    '__border-color--active':                     { "$value": "{theme.color.primary}" },
    '__border-color--disabled':                   { "$value": "{theme.color.gray.lighter}" },
    '__border-color--hover':                      { "$value": "{theme.color.primary}" },
    '__border-color':                             { "$value": "{theme.color.primary}" },
    '__color--active':                            { "$value": "{theme.color.primary}" },
    '__color--disabled':                          { "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$value": "{theme.color.primary}" },
    '__color':                                    { "$value": "{theme.color.white}" },
  },

  'button-solid-alt': {
    '__background-color--active':                 { "$value": "{theme.color.primary.lightest}" },
    '__background-color--disabled':               { "$value": "{theme.color.gray.lightest}" },
    '__background-color--hover':                  { "$value": "{theme.color.accent.primary}" },
    '__background-color':                         { "$value": "{theme.color.primary}" },
    '__border-color--active':                     { "$value": "{theme.color.primary}" },
    '__border-color--disabled':                   { "$value": "{theme.color.gray.lighter}" },
    '__border-color--hover':                      { "$value": "{theme.color.primary}" },
    '__border-color':                             { "$value": "{theme.color.primary}" },
    '__color--active':                            { "$value": "{theme.color.primary}" },
    '__color--disabled':                          { "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$value": "{theme.color.primary}" },
    '__color':                                    { "$value": "{theme.color.white}" },
  },

  'button-solid-dark': {
    '__background-color--active':                 { "$value": "{theme.color.gray.lighter}" },
    '__background-color--disabled':               { "$value": "{theme.color.gray.darker}" },
    '__background-color--hover':                  { "$value": "{theme.color.gray.lightest}" },
    '__background-color':                         { "$value": "{theme.color.white}" },
    '__border-color--active':                     { "$value": "{theme.color.gray.lighter}" },
    '__border-color--disabled':                   { "$value": "{theme.color.gray.darker}" },
    '__border-color--hover':                      { "$value": "{theme.color.gray.lightest}" },
    '__border-color':                             { "$value": "{theme.color.white}" },
    '__color--active':                            { "$value": "{theme.color.base}" },
    '__color--disabled':                          { "$value": "{theme.color.base}" },
    '__color--hover':                             { "$value": "{theme.color.base}" },
    '__color':                                    { "$value": "{theme.color.base}" },
  },

  'button-solid-dark-alt': {
    '__background-color--active':                 { "$value": "{theme.color.secondary}" },
    '__background-color--disabled':               { "$value": "{theme.color.gray.darker}" },
    '__background-color--hover':                  { "$value": "{theme.color.secondary.light}" },
    '__background-color':                         { "$value": "{theme.color.secondary.lighter}" },
    '__border-color--active':                     { "$value": "{theme.color.secondary}" },
    '__border-color--disabled':                   { "$value": "{theme.color.gray.darker}" },
    '__border-color--hover':                      { "$value": "{theme.color.secondary.light}" },
    '__border-color':                             { "$value": "{theme.color.secondary.lighter}" },
    '__color--active':                            { "$value": "{theme.color.base}" },
    '__color--disabled':                          { "$value": "{theme.color.base}" },
    '__color--hover':                             { "$value": "{theme.color.base}" },
    '__color':                                    { "$value": "{theme.color.base}" },
  },

  'button-ghost': {
    '__background-color--active':                 'transparent',
    '__background-color--disabled':               'transparent',
    '__background-color--hover':                  { "$value": "{theme.color.accent.primary}" },
    '__background-color':                         'transparent',
    '__border-color--active':                     'transparent',
    '__border-color--disabled':                   'transparent',
    '__border-color--hover':                      'transparent',
    '__border-color':                             'transparent',
    '__color--active':                            { "$value": "{theme.color.primary}" },
    '__color--disabled':                          { "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$value": "{theme.color.primary}" },
    '__color':                                    { "$value": "{theme.color.primary}" },
  },

  'button-ghost-alt': {
    '__background-color--active':                 'transparent',
    '__background-color--disabled':               'transparent',
    '__background-color--hover':                  { "$value": "{theme.color.accent.primary}" },
    '__background-color':                         'transparent',
    '__border-color--active':                     'transparent',
    '__border-color--disabled':                   'transparent',
    '__border-color--hover':                      'transparent',
    '__border-color':                             'transparent',
    '__color--active':                            { "$value": "{theme.color.primary}" },
    '__color--disabled':                          { "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$value": "{theme.color.primary}" },
    '__color':                                    { "$value": "{theme.color.primary}" },
  },

  'button-ghost-dark': {
    '__background-color--active':                 'transparent',
    '__background-color--disabled':               'transparent',
    '__background-color--hover':                  'transparent',
    '__background-color':                         'transparent',
    '__border-color--active':                     'transparent',
    '__border-color--disabled':                   'transparent',
    '__border-color--hover':                      'transparent',
    '__border-color':                             'transparent',
    '__color--active':                            { "$value": "{theme.color.gray.lighter}" },
    '__color--disabled':                          { "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$value": "{theme.color.gray.lightest}" },
    '__color':                                    { "$value": "{theme.color.white}" },
  },

  'button-ghost-dark-alt': {
    '__background-color--active':                 'transparent',
    '__background-color--disabled':               'transparent',
    '__background-color--hover':                  'transparent',
    '__background-color':                         'transparent',
    '__border-color--active':                     'transparent',
    '__border-color--disabled':                   'transparent',
    '__border-color--hover':                      'transparent',
    '__border-color':                             'transparent',
    '__color--active':                            { "$value": "{theme.color.secondary}" },
    '__color--disabled':                          { "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$value": "{theme.color.secondary.light}" },
    '__color':                                    { "$value": "{theme.color.secondary.lighter}" },
  },

  'choice': {
    '__background-color':                         { "$value": "{theme.color.background}" },
    '__background-color--checked':                { "$value": "{theme.color.primary}" },
    '__background-color--disabled':               { "$value": "{theme.color.gray.lighter}" },
    '__background-color--inverse':                { "$value": "{theme.color.transparent}" },
    '__background-color--disabled--inverse':      hexOpacity({ "$value": "{theme.color.muted.inverse}" }, 0.15),
    '__border-color':                             { "$value": "{theme.color.base}" },
    '__border-color--checked':                    { "$value": "{theme.color.primary}" },
    '__border-color--disabled':                   { "$value": "{theme.color.gray.light}" },
    '__border-color--error':                      { "$value": "{theme.color.base}" }, // Don't use error border for choice in this theme
    '__border-color--error--inverse':             { "$value": "{theme.color.white}" },
    '__border-color--inverse':                    { "$value": "{theme.color.white}" },
    '__border-color--left':                       { "$value": "{theme.color.primary}" },
    '__border-color--focus':                      { "$value": "{theme.color.primary.darker}" },
    '__border-color--disabled--inverse':          { "$value": "{theme.color.gray.light}" },
    '__border-radius':                            '0px',
    '__border-width':                             '2px',
    '__color--unchecked':                         { "$value": "{theme.color.white}" },
    '__color--disabled':                          { "$value": "{theme.color.muted}" },
    '__size':                                     { "$value": "{spacer.4}" },
    '__size--small':                              '20px',
    '__size-radio':                               '22px',
    '__size-radio--small':                        '12px',
    '-label__color--disabled':                    { "$value": "{theme.color.muted}" },
    '-label__color--disabled--inverse':           { "$value": "{theme.color.muted.inverse}" },
  },

  'day-picker': {
    '-button__background-color--hover':           { "$value": "{theme.color.primary.lightest}" },
  },

  'dialog': {
    '__background-color':                         { "$value": "{theme.color.white}" },
    '__padding':                                  { "$value": "{spacer.4}" },
    '-overlay__background-color':                 t.color['background-dialog-mask'],
    '-icon__size':                                '0.8125rem',
  },

  'drawer': {
    '__animation-timing':                         t.animation['speed-2'],
    '__background-color':                         { "$value": "{theme.color.background}" },
    '__border-color':                             { "$value": "{theme.color.border}" },
    '-close__color':                              { "$value": "{theme.color.black}" },
    '-header__background-color':                  { "$value": "{theme.color.gray.lightest}" },
    '-footer__background-color':                  { "$value": "{theme.color.info.lightest}" },
    '-toggle__background-color--hover':           { "$value": "{theme.color.info}" },
    '-toggle__color--hover':                      { "$value": "{theme.color.white}" },
    '-toggle__background-color--hover--inverse':  { "$value": "{theme.color.white}" },
    '-toggle__color--hover--inverse':             { "$value": "{theme.color.gray.darker}" },
  },

  'dropdown': {
    '__background-color':                         { "$value": "{theme.color.white}" },
    '-option-group__padding':                     { "$value": "{spacer.3}" },
  },

  'filter-chip': {
    '__border-radius':                            { "$value": "{radius.pill}" },
    '__background-color':                         { "$value": "{theme.color.primary.lightest}" },
    '__border-color':                             { "$value": "{theme.color.primary}" },
    '__color':                                    { "$value": "{theme.color.base}" },
    '__background-color--active':                 { "$value": "{theme.color.primary}" },
    '__border-color--active':                     { "$value": "{theme.color.primary}" },
    '__color--active':                            { "$value": "{theme.color.white}" },
    '-icon__color':                               { "$value": "{theme.color.base}" },
    '-icon__color-active':                        { "$value": "{theme.color.white}" },
    '-icon__container-size':                      '18px',
  },

  'form': {
    '__max-width':                                '460px',
    '__max-width--small':                         '6em',
    '__max-width--medium':                        '12em',
    '-hint__color':                               { "$value": "{theme.color.muted}" },
    '-hint__color--inverse':                      { "$value": "{theme.color.muted.inverse}" },
    '-error__color':                              { "$value": "{theme.color.error}" },
    '-error__color--inverse':                     { "$value": "{theme.color.error.light}" },
  },

  'icon': {
    '__color--error':                             { "$value": "{theme.color.error}" },
    '__color--inverse':                           { "$value": "{theme.color.white}" },
    '__color--primary':                           { "$value": "{theme.color.primary}" },
    '__color--success':                           { "$value": "{theme.color.success}" },
    '__color--warn':                              { "$value": "{theme.color.warn}" },
  },

  'label': {
    '__color--inverse':                           { "$value": "{theme.color.base.inverse}" },
    '__font-family':                              'inherit',
    '__font-size':                                'inherit',
    '__font-weight':                              t.font['weight-bold'],
    '__letter-spacing':                           'inherit',
    '__text-transform':                           'inherit',
  },

  'link': {
    '__color':                                    { "$value": "{theme.color.primary}" },
    '__color--active':                            { "$value": "{theme.color.base}" },
    '__color--hover':                             { "$value": "{theme.color.primary}" },
    '__color--visited':                           { "$value": "{theme.color.visited}" },
    '-inverse__color':                            { "$value": "{theme.color.base.inverse}" },
    '-inverse__color--active':                    { "$value": "{theme.color.muted.inverse}" },
    '-inverse__color--hover':                     { "$value": "{theme.color.muted.inverse}" },
    '-inverse__color--visited':                   { "$value": "{theme.color.muted.inverse}" },
    '__text-decoration-offset':                   '4px',
    '__text-decoration-thickness':                '2.4px',
    '__text-decoration-thickness--hover':         '2.4px',
  },

  'pagination': {
    '-link__color':                               { "$value": "{theme.color.primary}" },
    '-link__color--hover':                        { "$value": "{theme.color.primary.darker}" },
    '-link__color--active':                       { "$value": "{theme.color.primary.darkest}" },
    '-link__color--focus':                        { "$value": "{theme.color.primary.darker}" },
    '-link__color--disabled':                     { "$value": "{theme.color.gray.lighter}" },
    '-current-page__color':                       { "$value": "{theme.color.base}" },
    '-overflow__color':                           { "$value": "{theme.color.gray.dark}" },
    '-page-count__color':                         { "$value": "{theme.color.gray.dark}" },
  },

  'review': {
    '__border-color':                             { "$value": "{theme.color.border}" },
  },

  'steplist': {
    '__color':                                    { "$value": "{theme.color.muted}" },
    '__color--current':                           { "$value": "{theme.color.primary}" },
    '__background-color--current':                { "$value": "{theme.color.primary}" },
    '-step__color':                               { "$value": "{theme.color.muted}" },
    '-step__border-color':                        { "$value": "{theme.color.border}" },
    '-step__border-color--default':               { "$value": "{theme.color.muted}" },
    '-step__color--current':                      { "$value": "{theme.color.white}" },
    '-step__color--completed':                    { "$value": "{theme.color.base}" },
    '-step__background-color--completed':         { "$value": "{theme.color.base}" },
  },

  'spinner': {
    '__background-color':                         { "$value": "{theme.color.background}" },
    '__color':                                    { "$value": "{theme.color.base}" },
    '__background-color--inverse':                { "$value": "{theme.color.background.inverse}" },
    '__color--inverse':                           { "$value": "{theme.color.white}" },
  },

  'table': {
    '__padding':                                  { "$value": "{spacer.2}" },
    '__border-color':                             { "$value": "{theme.color.gray.lighter}" },
    '-header__background-color':                  { "$value": "{theme.color.primary.lightest}" },
    '-striped__background-color':                 { "$value": "{theme.color.gray.lightest}" },
    '-striped-header__background-color':          { "$value": "{theme.color.gray.lightest}" },
  },

  'tabs': {
    '__border-color':                             { "$value": "{theme.color.border}" },
    '__background-color':                         { "$value": "{theme.color.background}" },
    '__background-color--hover':                  { "$value": "{theme.color.primary.lightest}" },
    '__background-color--disabled':               { "$value": "{theme.color.gray.lighter}" },
    '__background-color--selected':               { "$value": "{theme.color.background}" },
    '__color':                                    { "$value": "{theme.color.base}" },
    '__color--hover':                             { "$value": "{theme.color.primary}" },
    '__color--active':                            { "$value": "{theme.color.primary.darker}" },
    '__color--disabled':                          { "$value": "{theme.color.gray.darker}" },
    '__color--selected':                          { "$value": "{theme.color.primary}" },
    '__border-color--disabled':                   { "$value": "{theme.color.gray.lighter}" },
    '__border-color--selected':                   { "$value": "{theme.color.primary}" },
    '-panel__background-color':                   { "$value": "{theme.color.background}" },
  },

  'text-input': {
    '__line-height':                              '1.3',
    '__background-color--disabled':               { "$value": "{theme.color.gray.lighter}" },
    '__border-width':                             '2px',
    '__border-width--error':                      '3px',
    '__border-color':                             { "$value": "{theme.color.base}" },
    '__border-color--disabled':                   { "$value": "{theme.color.gray.light}" },
    '__border-color--error':                      { "$value": "{theme.color.error}" },
    '__border-color--error--inverse':             { "$value": "{theme.color.error.light}" },
    '__border-color--inverse':                    { "$value": "{theme.color.black}" },
    '__color':                                    { "$value": "{theme.color.base}" },
    '__divider-color':                            { "$value": "{theme.color.gray.light}" },
    '__padding':                                  { "$value": "{spacer.1}" },
    '__border-radius':                            { "$value": "{radius.default}" },
  },

  'tooltip': {
    '__background-color':                         { "$value": "{theme.color.background}" },
    '__border-color':                             { "$value": "{theme.color.gray.darker}" },
    '__border-color--active':                     hexOpacity({ "$value": "{theme.color.primary}" }, 0.25),
    '__border-color--inverse-active':             hexOpacity({ "$value": "{theme.color.white}" }, 0.25),
    '__border-width':                             '1px',
    '__color':                                    { "$value": "{theme.color.base}" },
    '__box-shadow-color':                         { "$value": "{theme.color.gray.light}" },
    '-icon__color':                               { "$value": "{theme.color.primary}" },
    '-icon__color--inverse':                      { "$value": "{theme.color.white}" },
    '-trigger__color':                            { "$value": "{theme.color.primary}" },
  },

  'typography-heading': {
    '__font-family':                              'inherit',
    '__font-weight':                              t.font['weight-bold'],
    '-4xl__font-weight':                          'inherit',
    '-3xl__font-weight':                          'inherit',
    '-lg__font-weight':                           t.font['weight-bold'],
    '-md__font-weight':                           t.font['weight-bold'],
    '-sm__font-weight':                           t.font['weight-normal'],
    '-sm__font-size':                             t.font['size-sm'],
    '-md__font-size':                             t.font['size-md'],
    '-lg__font-size':                             t.font['size-lg'],
    '-xl__font-size':                             t.font['size-xl'],
    '-2xl__font-size--mobile':                    t.font['size-2xl--mobile'],
    '-2xl__font-size':                            t.font['size-2xl'],
    '-3xl__font-size--mobile':                    t.font['size-3xl--mobile'],
    '-3xl__font-size':                            t.font['size-3xl'],
    '-4xl__font-size--mobile':                    t.font['size-4xl--mobile'],
    '-4xl__font-size':                            t.font['size-4xl'],
    '-5xl__font-size--mobile':                    t.font['size-5xl--mobile'],
    '-5xl__font-size--tablet':                    t.font['size-5xl--tablet'],
    '-5xl__font-size':                            t.font['size-5xl'],
  },

  'typography-body': {
    '__font-family':                              t.font['sans'],
  },

  'usa-banner': {
    '__background-color':                         { "$value": "{theme.color.gray.lightest}" },
    '__color':                                    { "$value": "{theme.color.base}" },
    '__max-width':                                t.global['site-max-width'],
    '-gutter-width':                              t.global['grid-gutter-width'],
    '-heading__font-family':                      t.font['sans'],
    '-heading__line-height':                      '1.1',
    '-heading__font-size':                        t.font['size-sm'],
    '-panel__font-family':                        t.font['sans'],
    '-panel__line-height':                        t.font['line-height-base'],
    '-panel__font-size':                          t.font['size-base'],
    '-link__color':                               { "$value": "{theme.color.primary}" },
    '-domain-icon__color':                        { "$value": "{theme.color.primary}" },
    '-security-icon__color':                      { "$value": "{theme.color.success.light}" },
    '-close-button__background-color--mobile':    { "$value": "{theme.color.gray.lighter}" },
    '-close-button__color--mobile':               { "$value": "{theme.color.primary}" },
  },

  'vertical-nav': {
    '-item__background-color--hover':             { "$value": "{theme.color.gray.lightest}" },
    '-item__color--hover':                        { "$value": "{theme.color.primary}" },
    '-item__border-color':                        { "$value": "{theme.color.gray.dark}" },
    '-label__color':                              { "$value": "{theme.color.base}" },
    '-label-icon__color':                         { "$value": "{theme.color.base}" },
    '-label__border-color--current':              { "$value": "{theme.color.primary}" },
    '-label__color--current':                     { "$value": "{theme.color.primary}" },
  },
};

export default components
