/*
 * CMSgov CMSDS Component Theme
 */

import { default as t } from './cmsgov'
import { hexOpacity } from '../lib/colorUtils'
import { AnyTokenValues } from '../lib/types'

// Write a little script that goes through each component and turns each property into an object
// with a type derived by pattern matching the property name.
// if prefixed with __, it goes in the current object
// if prefixed with -, it goes in a new sub-object (not in a siblng object, because we want to
//   maintain the hierarchy)

export const components: AnyTokenValues = {
  'accordion': {
    '__color':                                    { "$type": "color", "$value": "{theme.color.base}" },
    '__background-color':                         { "$type": "color", "$value": "{theme.color.primary.lightest}" },
    '__background-color--hover':                  { "$type": "color", "$value": "{theme.color.primary.lighter}" },
    '__border-color':                             { "$type": "color", "$value": "{theme.color.gray.lightest}" },
    '__border-radius':                            '20px 20px 0 0',
    '__border-width':                             { "$type": "dimension", "$value": "1px" },
    '-button__color':                             { "$type": "color", "$value": "{theme.color.base}" },
    '-content__background-color':                 { "$type": "color", "$value": "{theme.color.white}" },
  },

  'alert': {
    '__background-color':                         { "$type": "color", "$value": "{theme.color.info.lightest}" },
    '__background-color--error':                  { "$type": "color", "$value": "{theme.color.error.lightest}" },
    '__background-color--lightweight':            { "$type": "color", "$value": "{theme.color.white}" },
    '__background-color--success':                { "$type": "color", "$value": "{theme.color.success.lightest}" },
    '__background-color--warn':                   { "$type": "color", "$value": "{theme.color.warn.lightest}" },
    '__border-left-color':                        { "$type": "color", "$value": "{theme.color.info}" },
    '__border-color--error':                      { "$type": "color", "$value": "{theme.color.error}" },
    '__border-color--success':                    { "$type": "color", "$value": "{theme.color.success}" },
    '__border-color--warn':                       { "$type": "color", "$value": "{theme.color.warn}" },
    '__font-color':                               { "$type": "color", "$value": "{theme.color.base}" },
    '__icon-size':                                { "$value": "{spacer.5}" },
    '__padding':                                  { "$value": "{spacer.2}" },
    '-bar__width':                                { "$value": "{spacer.1}" },
    '-link__font-color':                          { "$type": "color", "$value": "{theme.color.primary.darker}" },
    '-link__font-color--hover':                   { "$type": "color", "$value": "{theme.color.primary.darkest}" },
    '-link__font-color--focus':                   { "$type": "color", "$value": "{theme.color.primary.darkest}" },
    '-link__font-color--active':                  { "$type": "color", "$value": "{theme.color.primary.darkest}" },
  },

  'autocomplete': {
    '__background-color':                         { "$type": "color", "$value": "{theme.color.white}" },
    '__border-color':                             { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '-item__font-color':                          { "$type": "color", "$value": "{theme.color.primary}" },
    '-item__background-color--active':            { "$type": "color", "$value": "{theme.color.primary}" },
    '-item__font-color--active':                  { "$type": "color", "$value": "{theme.color.white}" },
    '-item-message__font-color':                  { "$type": "color", "$value": "{theme.color.primary}" },
  },

  'badge': {
    '__background-color':                         { "$type": "color", "$value": "{theme.color.gray.lightest}" },
    '__background-color--alert':                  { "$type": "color", "$value": "{theme.color.error}" },
    '__background-color--info':                   { "$type": "color", "$value": "{theme.color.primary}" },
    '__background-color--success':                { "$type": "color", "$value": "{theme.color.success}" },
    '__background-color--warn':                   { "$type": "color", "$value": "{theme.color.warn}" },
    '__font-color':                               { "$type": "color", "$value": "{theme.color.base}" },
    '__font-color--alert':                        { "$type": "color", "$value": "{theme.color.white}" },
    '__font-color--info':                         { "$type": "color", "$value": "{theme.color.white}" },
    '__font-color--success':                      { "$type": "color", "$value": "{theme.color.white}" },
    '__font-color--warn':                         { "$type": "color", "$value": "{theme.color.base}" },
    '__border-radius':                            { "$value": "{radius.medium}" },
  },

  'button': {
    '__background-color--active':                 { "$type": "color", "$value": "{theme.color.primary.lightest}" },
    '__background-color--disabled':               { "$type": "color", "$value": "{theme.color.gray.lightest}" },
    '__background-color--hover':                  { "$type": "color", "$value": "{theme.color.accent.primary}" },
    '__background-color':                         { "$type": "color", "$value": "transparent" },
    '__border-color--active':                     { "$type": "color", "$value": "{theme.color.primary}" },
    '__border-color--disabled':                   { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '__border-color--hover':                      { "$type": "color", "$value": "{theme.color.primary}" },
    '__border-color':                             { "$type": "color", "$value": "{theme.color.primary}" },
    '__border-radius':                            { "$value": "{radius.pill}" },
    '__border-width':                             { "$type": "dimension", "$value": "2px" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.primary.darkest}" },
    '__color--disabled':                          { "$type": "color", "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$type": "color", "$value": "{theme.color.primary.darker}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.primary}" },
    '__font-weight':                              { "$value": "{theme.font.weight.bold}" },
    '-icon__fill':                                { "$type": "color", "$value": "currentColor" },
  },

  'button-alt': {
    '__background-color--active':                 { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '__background-color--disabled':               { "$type": "color", "$value": "transparent" },
    '__background-color--hover':                  { "$type": "color", "$value": "{theme.color.accent.primary}" },
    '__background-color':                         { "$type": "color", "$value": "transparent" },
    '__border-color--active':                     { "$type": "color", "$value": "currentColor" },
    '__border-color--disabled':                   { "$type": "color", "$value": "currentColor" },
    '__border-color--hover':                      { "$type": "color", "$value": "currentColor" },
    '__border-color':                             { "$type": "color", "$value": "currentColor" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.primary.darkest}" },
    '__color--disabled':                          { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '__color--hover':                             { "$type": "color", "$value": "{theme.color.primary.darker}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.primary}" },
  },

  'button-dark': {
    '__background-color--active':                 { "$type": "color", "$value": "transparent" },
    '__background-color--disabled':               { "$type": "color", "$value": "transparent" },
    '__background-color--hover':                  { "$type": "color", "$value": "transparent" },
    '__background-color':                         { "$type": "color", "$value": "transparent" },
    '__border-color--active':                     { "$type": "color", "$value": "currentColor" },
    '__border-color--disabled':                   { "$type": "color", "$value": "currentColor" },
    '__border-color--hover':                      { "$type": "color", "$value": "currentColor" },
    '__border-color':                             { "$type": "color", "$value": "currentColor" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '__color--disabled':                          { "$type": "color", "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$type": "color", "$value": "{theme.color.gray.lightest}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.white}" },
  },

  'button-dark-alt': {
    '__background-color--active':                 { "$type": "color", "$value": "transparent" },
    '__background-color--disabled':               { "$type": "color", "$value": "transparent" },
    '__background-color--hover':                  { "$type": "color", "$value": "transparent" },
    '__background-color':                         { "$type": "color", "$value": "transparent" },
    '__border-color--active':                     { "$type": "color", "$value": "currentColor" },
    '__border-color--disabled':                   { "$type": "color", "$value": "currentColor" },
    '__border-color--hover':                      { "$type": "color", "$value": "currentColor" },
    '__border-color':                             { "$type": "color", "$value": "currentColor" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.secondary.light}" },
    '__color--disabled':                          { "$type": "color", "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$type": "color", "$value": "{theme.color.secondary.lighter}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.secondary.lightest}" },
  },

  'button-solid': {
    '__background-color--active':                 { "$type": "color", "$value": "{theme.color.primary.lightest}" },
    '__background-color--disabled':               { "$type": "color", "$value": "{theme.color.gray.lightest}" },
    '__background-color--hover':                  { "$type": "color", "$value": "{theme.color.accent.primary}" },
    '__background-color':                         { "$type": "color", "$value": "{theme.color.primary}" },
    '__border-color--active':                     { "$type": "color", "$value": "{theme.color.primary}" },
    '__border-color--disabled':                   { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '__border-color--hover':                      { "$type": "color", "$value": "{theme.color.primary}" },
    '__border-color':                             { "$type": "color", "$value": "{theme.color.primary}" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.primary}" },
    '__color--disabled':                          { "$type": "color", "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$type": "color", "$value": "{theme.color.primary}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.white}" },
  },

  'button-solid-alt': {
    '__background-color--active':                 { "$type": "color", "$value": "{theme.color.primary.lightest}" },
    '__background-color--disabled':               { "$type": "color", "$value": "{theme.color.gray.lightest}" },
    '__background-color--hover':                  { "$type": "color", "$value": "{theme.color.accent.primary}" },
    '__background-color':                         { "$type": "color", "$value": "{theme.color.primary}" },
    '__border-color--active':                     { "$type": "color", "$value": "{theme.color.primary}" },
    '__border-color--disabled':                   { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '__border-color--hover':                      { "$type": "color", "$value": "{theme.color.primary}" },
    '__border-color':                             { "$type": "color", "$value": "{theme.color.primary}" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.primary}" },
    '__color--disabled':                          { "$type": "color", "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$type": "color", "$value": "{theme.color.primary}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.white}" },
  },

  'button-solid-dark': {
    '__background-color--active':                 { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '__background-color--disabled':               { "$type": "color", "$value": "{theme.color.gray.darker}" },
    '__background-color--hover':                  { "$type": "color", "$value": "{theme.color.gray.lightest}" },
    '__background-color':                         { "$type": "color", "$value": "{theme.color.white}" },
    '__border-color--active':                     { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '__border-color--disabled':                   { "$type": "color", "$value": "{theme.color.gray.darker}" },
    '__border-color--hover':                      { "$type": "color", "$value": "{theme.color.gray.lightest}" },
    '__border-color':                             { "$type": "color", "$value": "{theme.color.white}" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.base}" },
    '__color--disabled':                          { "$type": "color", "$value": "{theme.color.base}" },
    '__color--hover':                             { "$type": "color", "$value": "{theme.color.base}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.base}" },
  },

  'button-solid-dark-alt': {
    '__background-color--active':                 { "$type": "color", "$value": "{theme.color.secondary}" },
    '__background-color--disabled':               { "$type": "color", "$value": "{theme.color.gray.darker}" },
    '__background-color--hover':                  { "$type": "color", "$value": "{theme.color.secondary.light}" },
    '__background-color':                         { "$type": "color", "$value": "{theme.color.secondary.lighter}" },
    '__border-color--active':                     { "$type": "color", "$value": "{theme.color.secondary}" },
    '__border-color--disabled':                   { "$type": "color", "$value": "{theme.color.gray.darker}" },
    '__border-color--hover':                      { "$type": "color", "$value": "{theme.color.secondary.light}" },
    '__border-color':                             { "$type": "color", "$value": "{theme.color.secondary.lighter}" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.base}" },
    '__color--disabled':                          { "$type": "color", "$value": "{theme.color.base}" },
    '__color--hover':                             { "$type": "color", "$value": "{theme.color.base}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.base}" },
  },

  'button-ghost': {
    '__background-color--active':                 { "$type": "color", "$value": "transparent" },
    '__background-color--disabled':               { "$type": "color", "$value": "transparent" },
    '__background-color--hover':                  { "$type": "color", "$value": "{theme.color.accent.primary}" },
    '__background-color':                         { "$type": "color", "$value": "transparent" },
    '__border-color--active':                     { "$type": "color", "$value": "transparent" },
    '__border-color--disabled':                   { "$type": "color", "$value": "transparent" },
    '__border-color--hover':                      { "$type": "color", "$value": "transparent" },
    '__border-color':                             { "$type": "color", "$value": "transparent" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.primary}" },
    '__color--disabled':                          { "$type": "color", "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$type": "color", "$value": "{theme.color.primary}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.primary}" },
  },

  'button-ghost-alt': {
    '__background-color--active':                 { "$type": "color", "$value": "transparent" },
    '__background-color--disabled':               { "$type": "color", "$value": "transparent" },
    '__background-color--hover':                  { "$type": "color", "$value": "{theme.color.accent.primary}" },
    '__background-color':                         { "$type": "color", "$value": "transparent" },
    '__border-color--active':                     { "$type": "color", "$value": "transparent" },
    '__border-color--disabled':                   { "$type": "color", "$value": "transparent" },
    '__border-color--hover':                      { "$type": "color", "$value": "transparent" },
    '__border-color':                             { "$type": "color", "$value": "transparent" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.primary}" },
    '__color--disabled':                          { "$type": "color", "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$type": "color", "$value": "{theme.color.primary}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.primary}" },
  },

  'button-ghost-dark': {
    '__background-color--active':                 { "$type": "color", "$value": "transparent" },
    '__background-color--disabled':               { "$type": "color", "$value": "transparent" },
    '__background-color--hover':                  { "$type": "color", "$value": "transparent" },
    '__background-color':                         { "$type": "color", "$value": "transparent" },
    '__border-color--active':                     { "$type": "color", "$value": "transparent" },
    '__border-color--disabled':                   { "$type": "color", "$value": "transparent" },
    '__border-color--hover':                      { "$type": "color", "$value": "transparent" },
    '__border-color':                             { "$type": "color", "$value": "transparent" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '__color--disabled':                          { "$type": "color", "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$type": "color", "$value": "{theme.color.gray.lightest}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.white}" },
  },

  'button-ghost-dark-alt': {
    '__background-color--active':                 { "$type": "color", "$value": "transparent" },
    '__background-color--disabled':               { "$type": "color", "$value": "transparent" },
    '__background-color--hover':                  { "$type": "color", "$value": "transparent" },
    '__background-color':                         { "$type": "color", "$value": "transparent" },
    '__border-color--active':                     { "$type": "color", "$value": "transparent" },
    '__border-color--disabled':                   { "$type": "color", "$value": "transparent" },
    '__border-color--hover':                      { "$type": "color", "$value": "transparent" },
    '__border-color':                             { "$type": "color", "$value": "transparent" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.secondary}" },
    '__color--disabled':                          { "$type": "color", "$value": "{theme.color.gray.dark}" },
    '__color--hover':                             { "$type": "color", "$value": "{theme.color.secondary.light}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.secondary.lighter}" },
  },

  'choice': {
    '__background-color':                         { "$type": "color", "$value": "{theme.color.background}" },
    '__background-color--checked':                { "$type": "color", "$value": "{theme.color.primary}" },
    '__background-color--disabled':               { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '__background-color--inverse':                { "$type": "color", "$value": "{theme.color.transparent}" },
    '__background-color--disabled--inverse':      { "$value": "{hexOpacity(theme.color.muted.inverse, 0.15)}" },
    '__border-color':                             { "$type": "color", "$value": "{theme.color.base}" },
    '__border-color--checked':                    { "$type": "color", "$value": "{theme.color.primary}" },
    '__border-color--disabled':                   { "$type": "color", "$value": "{theme.color.gray.light}" },
    '__border-color--error':                      { "$type": "color", "$value": "{theme.color.base}" }, // Don't use error border for choice in this theme
    '__border-color--error--inverse':             { "$type": "color", "$value": "{theme.color.white}" },
    '__border-color--inverse':                    { "$type": "color", "$value": "{theme.color.white}" },
    '__border-color--left':                       { "$type": "color", "$value": "{theme.color.primary}" },
    '__border-color--focus':                      { "$type": "color", "$value": "{theme.color.primary.darker}" },
    '__border-color--disabled--inverse':          { "$type": "color", "$value": "{theme.color.gray.light}" },
    '__border-radius':                            { "$type": "dimension", "$value": "0px" },
    '__border-width':                             { "$type": "dimension", "$value": "2px" },
    '__color--unchecked':                         { "$type": "color", "$value": "{theme.color.white}" },
    '__color--disabled':                          { "$type": "color", "$value": "{theme.color.muted}" },
    '__size':                                     { "$value": "{spacer.4}" },
    '__size--small':                              { "$type": "dimension", "$value": "20px" },
    '__size-radio':                               { "$type": "dimension", "$value": "22px" },
    '__size-radio--small':                        { "$type": "dimension", "$value": "12px" },
    '-label__color--disabled':                    { "$type": "color", "$value": "{theme.color.muted}" },
    '-label__color--disabled--inverse':           { "$type": "color", "$value": "{theme.color.muted.inverse}" },
  },

  'day-picker': {
    '-button__background-color--hover':           { "$type": "color", "$value": "{theme.color.primary.lightest}" },
  },

  'dialog': {
    '__background-color':                         { "$type": "color", "$value": "{theme.color.white}" },
    '__padding':                                  { "$value": "{spacer.4}" },
    '-overlay__background-color':                 { "$type": "color", "$value": "{theme.color.background-dialog-mask}" },
    '-icon__size':                                { "$type": "dimension", "$value": "0.8125rem" },
  },

  'drawer': {
    '__animation-timing':                         { "$value": "{animation.speed.2}" },
    '__background-color':                         { "$type": "color", "$value": "{theme.color.background}" },
    '__border-color':                             { "$type": "color", "$value": "{theme.color.border}" },
    '-close__color':                              { "$type": "color", "$value": "{theme.color.black}" },
    '-header__background-color':                  { "$type": "color", "$value": "{theme.color.gray.lightest}" },
    '-footer__background-color':                  { "$type": "color", "$value": "{theme.color.info.lightest}" },
    '-toggle__background-color--hover':           { "$type": "color", "$value": "{theme.color.info}" },
    '-toggle__color--hover':                      { "$type": "color", "$value": "{theme.color.white}" },
    '-toggle__background-color--hover--inverse':  { "$type": "color", "$value": "{theme.color.white}" },
    '-toggle__color--hover--inverse':             { "$type": "color", "$value": "{theme.color.gray.darker}" },
  },

  'dropdown': {
    '__background-color':                         { "$type": "color", "$value": "{theme.color.white}" },
    '-option-group__padding':                     { "$value": "{spacer.3}" },
  },

  'filter-chip': {
    '__border-radius':                            { "$value": "{radius.pill}" },
    '__background-color':                         { "$type": "color", "$value": "{theme.color.primary.lightest}" },
    '__border-color':                             { "$type": "color", "$value": "{theme.color.primary}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.base}" },
    '__background-color--active':                 { "$type": "color", "$value": "{theme.color.primary}" },
    '__border-color--active':                     { "$type": "color", "$value": "{theme.color.primary}" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.white}" },
    '-icon__color':                               { "$type": "color", "$value": "{theme.color.base}" },
    '-icon__color-active':                        { "$type": "color", "$value": "{theme.color.white}" },
    '-icon__container-size':                      { "$type": "dimension", "$value": "18px" },
  },

  'form': {
    '__max-width':                                { "$type": "dimension", "$value": "460px" },
    '__max-width--small':                         { "$type": "dimension", "$value": "6em" },
    '__max-width--medium':                        { "$type": "dimension", "$value": "12em" },
    '-hint__color':                               { "$type": "color", "$value": "{theme.color.muted}" },
    '-hint__color--inverse':                      { "$type": "color", "$value": "{theme.color.muted.inverse}" },
    '-error__color':                              { "$type": "color", "$value": "{theme.color.error}" },
    '-error__color--inverse':                     { "$type": "color", "$value": "{theme.color.error.light}" },
  },

  'icon': {
    '__color--error':                             { "$type": "color", "$value": "{theme.color.error}" },
    '__color--inverse':                           { "$type": "color", "$value": "{theme.color.white}" },
    '__color--primary':                           { "$type": "color", "$value": "{theme.color.primary}" },
    '__color--success':                           { "$type": "color", "$value": "{theme.color.success}" },
    '__color--warn':                              { "$type": "color", "$value": "{theme.color.warn}" },
  },

  'label': {
    '__color--inverse':                           { "$type": "color", "$value": "{theme.color.base.inverse}" },
    '__font-family':                              'inherit',
    '__font-size':                                'inherit',
    '__font-weight':                              { "$value": "{theme.font.weight.bold}" },
    '__letter-spacing':                           'inherit',
    '__text-transform':                           'inherit',
  },

  'link': {
    '__color':                                    { "$type": "color", "$value": "{theme.color.primary}" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.base}" },
    '__color--hover':                             { "$type": "color", "$value": "{theme.color.primary}" },
    '__color--visited':                           { "$type": "color", "$value": "{theme.color.visited}" },
    '-inverse__color':                            { "$type": "color", "$value": "{theme.color.base.inverse}" },
    '-inverse__color--active':                    { "$type": "color", "$value": "{theme.color.muted.inverse}" },
    '-inverse__color--hover':                     { "$type": "color", "$value": "{theme.color.muted.inverse}" },
    '-inverse__color--visited':                   { "$type": "color", "$value": "{theme.color.muted.inverse}" },
    '__text-decoration-offset':                   { "$type": "dimension", "$value": "4px" },
    '__text-decoration-thickness':                { "$type": "dimension", "$value": "2.4px" },
    '__text-decoration-thickness--hover':         { "$type": "dimension", "$value": "2.4px" },
  },

  'pagination': {
    '-link__color':                               { "$type": "color", "$value": "{theme.color.primary}" },
    '-link__color--hover':                        { "$type": "color", "$value": "{theme.color.primary.darker}" },
    '-link__color--active':                       { "$type": "color", "$value": "{theme.color.primary.darkest}" },
    '-link__color--focus':                        { "$type": "color", "$value": "{theme.color.primary.darker}" },
    '-link__color--disabled':                     { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '-current-page__color':                       { "$type": "color", "$value": "{theme.color.base}" },
    '-overflow__color':                           { "$type": "color", "$value": "{theme.color.gray.dark}" },
    '-page-count__color':                         { "$type": "color", "$value": "{theme.color.gray.dark}" },
  },

  'review': {
    '__border-color':                             { "$type": "color", "$value": "{theme.color.border}" },
  },

  'steplist': {
    '__color':                                    { "$type": "color", "$value": "{theme.color.muted}" },
    '__color--current':                           { "$type": "color", "$value": "{theme.color.primary}" },
    '__background-color--current':                { "$type": "color", "$value": "{theme.color.primary}" },
    '-step__color':                               { "$type": "color", "$value": "{theme.color.muted}" },
    '-step__border-color':                        { "$type": "color", "$value": "{theme.color.border}" },
    '-step__border-color--default':               { "$type": "color", "$value": "{theme.color.muted}" },
    '-step__color--current':                      { "$type": "color", "$value": "{theme.color.white}" },
    '-step__color--completed':                    { "$type": "color", "$value": "{theme.color.base}" },
    '-step__background-color--completed':         { "$type": "color", "$value": "{theme.color.base}" },
  },

  'spinner': {
    '__background-color':                         { "$type": "color", "$value": "{theme.color.background}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.base}" },
    '__background-color--inverse':                { "$type": "color", "$value": "{theme.color.background.inverse}" },
    '__color--inverse':                           { "$type": "color", "$value": "{theme.color.white}" },
  },

  'table': {
    '__padding':                                  { "$value": "{spacer.2}" },
    '__border-color':                             { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '-header__background-color':                  { "$type": "color", "$value": "{theme.color.primary.lightest}" },
    '-striped__background-color':                 { "$type": "color", "$value": "{theme.color.gray.lightest}" },
    '-striped-header__background-color':          { "$type": "color", "$value": "{theme.color.gray.lightest}" },
  },

  'tabs': {
    '__border-color':                             { "$type": "color", "$value": "{theme.color.border}" },
    '__background-color':                         { "$type": "color", "$value": "{theme.color.background}" },
    '__background-color--hover':                  { "$type": "color", "$value": "{theme.color.primary.lightest}" },
    '__background-color--disabled':               { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '__background-color--selected':               { "$type": "color", "$value": "{theme.color.background}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.base}" },
    '__color--hover':                             { "$type": "color", "$value": "{theme.color.primary}" },
    '__color--active':                            { "$type": "color", "$value": "{theme.color.primary.darker}" },
    '__color--disabled':                          { "$type": "color", "$value": "{theme.color.gray.darker}" },
    '__color--selected':                          { "$type": "color", "$value": "{theme.color.primary}" },
    '__border-color--disabled':                   { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '__border-color--selected':                   { "$type": "color", "$value": "{theme.color.primary}" },
    '-panel__background-color':                   { "$type": "color", "$value": "{theme.color.background}" },
  },

  'text-input': {
    '__line-height':                              '1.3',
    '__background-color--disabled':               { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '__border-width':                             { "$type": "dimension", "$value": "2px" },
    '__border-width--error':                      { "$type": "dimension", "$value": "3px" },
    '__border-color':                             { "$type": "color", "$value": "{theme.color.base}" },
    '__border-color--disabled':                   { "$type": "color", "$value": "{theme.color.gray.light}" },
    '__border-color--error':                      { "$type": "color", "$value": "{theme.color.error}" },
    '__border-color--error--inverse':             { "$type": "color", "$value": "{theme.color.error.light}" },
    '__border-color--inverse':                    { "$type": "color", "$value": "{theme.color.black}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.base}" },
    '__divider-color':                            { "$type": "color", "$value": "{theme.color.gray.light}" },
    '__padding':                                  { "$value": "{spacer.1}" },
    '__border-radius':                            { "$value": "{radius.default}" },
  },

  'tooltip': {
    '__background-color':                         { "$type": "color", "$value": "{theme.color.background}" },
    '__border-color':                             { "$type": "color", "$value": "{theme.color.gray.darker}" },
    '__border-color--active':                     { "$value": "{hexOpacity(theme.color.primary, 0.25)}" },
    '__border-color--inverse-active':             { "$value": "{hexOpacity(theme.color.white, 0.25)}" },
    '__border-width':                             { "$type": "dimension", "$value": "1px" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.base}" },
    '__box-shadow-color':                         { "$type": "color", "$value": "{theme.color.gray.light}" },
    '-icon__color':                               { "$type": "color", "$value": "{theme.color.primary}" },
    '-icon__color--inverse':                      { "$type": "color", "$value": "{theme.color.white}" },
    '-trigger__color':                            { "$type": "color", "$value": "{theme.color.primary}" },
  },

  'typography-heading': {
    '__font-family':                              'inherit',
    '__font-weight':                              { "$value": "{theme.font.weight.bold}" },
    '-4xl__font-weight':                          'inherit',
    '-3xl__font-weight':                          'inherit',
    '-lg__font-weight':                           { "$value": "{theme.font.weight.bold}" },
    '-md__font-weight':                           { "$value": "{theme.font.weight.bold}" },
    '-sm__font-weight':                           { "$value": "{theme.font.weight.normal}" },
    '-sm__font-size':                             { "$value": "{theme.font.size.sm}" },
    '-md__font-size':                             { "$value": "{theme.font.size.md}" },
    '-lg__font-size':                             { "$value": "{theme.font.size.lg}" },
    '-xl__font-size':                             { "$value": "{theme.font.size.xl}" },
    '-2xl__font-size--mobile':                    { "$value": "{theme.font.size.2xl--mobile}" },
    '-2xl__font-size':                            { "$value": "{theme.font.size.2xl}" },
    '-3xl__font-size--mobile':                    { "$value": "{theme.font.size.3xl--mobile}" },
    '-3xl__font-size':                            { "$value": "{theme.font.size.3xl}" },
    '-4xl__font-size--mobile':                    { "$value": "{theme.font.size.4xl--mobile}" },
    '-4xl__font-size':                            { "$value": "{theme.font.size.4xl}" },
    '-5xl__font-size--mobile':                    { "$value": "{theme.font.size.5xl--mobile}" },
    '-5xl__font-size--tablet':                    { "$value": "{theme.font.size.5xl--tablet}" },
    '-5xl__font-size':                            { "$value": "{theme.font.size.5xl}" },
  },

  'typography-body': {
    '__font-family':                              { "$value": "{theme.font.sans}" },
  },

  'usa-banner': {
    '__background-color':                         { "$type": "color", "$value": "{theme.color.gray.lightest}" },
    '__color':                                    { "$type": "color", "$value": "{theme.color.base}" },
    '__max-width':                                { "$value": "{site-max-width}" },
    '-gutter-width':                              { "$value": "{grid.gutter-width}" },
    '-heading__font-family':                      { "$value": "{theme.font.sans}" },
    '-heading__line-height':                      '1.1',
    '-heading__font-size':                        { "$value": "{theme.font.size.sm}" },
    '-panel__font-family':                        { "$value": "{theme.font.sans}" },
    '-panel__line-height':                        { "$value": "{theme.font.line-height-base}" },
    '-panel__font-size':                          { "$value": "{theme.font.size.base}" },
    '-link__color':                               { "$type": "color", "$value": "{theme.color.primary}" },
    '-domain-icon__color':                        { "$type": "color", "$value": "{theme.color.primary}" },
    '-security-icon__color':                      { "$type": "color", "$value": "{theme.color.success.light}" },
    '-close-button__background-color--mobile':    { "$type": "color", "$value": "{theme.color.gray.lighter}" },
    '-close-button__color--mobile':               { "$type": "color", "$value": "{theme.color.primary}" },
  },

  'vertical-nav': {
    '-item__background-color--hover':             { "$type": "color", "$value": "{theme.color.gray.lightest}" },
    '-item__color--hover':                        { "$type": "color", "$value": "{theme.color.primary}" },
    '-item__border-color':                        { "$type": "color", "$value": "{theme.color.gray.dark}" },
    '-label__color':                              { "$type": "color", "$value": "{theme.color.base}" },
    '-label-icon__color':                         { "$type": "color", "$value": "{theme.color.base}" },
    '-label__border-color--current':              { "$type": "color", "$value": "{theme.color.primary}" },
    '-label__color--current':                     { "$type": "color", "$value": "{theme.color.primary}" },
  },
};

export default components
